export const en = {
  title: 'FlowReport Designer',
  file: 'File',
  edit: 'Edit',
  view: 'View',
  import: 'Import XML',
  export: 'Export XML',
  preview: 'Preview',
  designer: 'Designer',
  save: 'Save',
  addPage: 'Add Page',
  structure: 'Structure',
  properties: 'Properties',
  toolbox: 'Toolbox',
  text: 'Text',
  image: 'Image',
  hLayout: 'H-Layout',
  vLayout: 'V-Layout',
  table: 'Table',
  pageSettings: 'Page Settings',
  pageSize: 'Page Size',
  orientation: 'Orientation',
  portrait: 'Portrait',
  landscape: 'Landscape',
  pageRegions: 'Page Regions',
  showHeader: 'Show Header',
  showFooter: 'Show Footer',
  general: 'General',
  name: 'Name',
  content: 'Content',
  imageUrl: 'Image URL',
  tableCell: 'Table Cell',
  colSpan: 'Col Span',
  rowSpan: 'Row Span',
  layoutSpacing: 'Layout & Spacing',
  padding: 'Padding',
  margin: 'Margin',
  width: 'Width',
  height: 'Height',
  minHeight: 'Min Height',
  flex: 'Flex',
  typography: 'Typography',
  fontSize: 'Font Size',
  fontFamily: 'Font Family',
  alignment: 'Alignment',
  left: 'Left',
  center: 'Center',
  right: 'Right',
  colors: 'Colors',
  textColor: 'Text Color',
  bgColor: 'Background',
  border: 'Border',
  borderWidth: 'Border Width',
  borderStyle: 'Border Style',
  borderColor: 'Border Color',
  borderRadius: 'Radius',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  strikethrough: 'Strikethrough',
  vAlign: 'V-Align',
  top: 'Top',
  middle: 'Middle',
  bottom: 'Bottom',
  none: 'None',
  solid: 'Solid',
  dashed: 'Dashed',
  dotted: 'Dotted',
  double: 'Double',
  clear: 'Clear',
  rows: 'Rows',
  cols: 'Cols',
  flexbox: 'Flexbox',
  gap: 'Gap',
  justify: 'Justify',
  align: 'Align',
  columnWidths: 'Column Widths',
  dataSource: 'Data Source',
  dataSourceUrl: 'Data Source URL',
  fetchData: 'Fetch Data',
  systemFields: 'System Fields',
  tables: 'Tables',
  columns: 'Columns',
  selectColumns: 'Select Columns',
  cancel: 'Cancel',
  confirm: 'Confirm',
  selectToEdit: 'Select a component to edit',
};
